spring:
  application:
    name: IDUS Task API

  datasource:
    url: jdbc:mysql://localhost:3306/idus?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: idus
    password: Idus-task
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  jwt:
    secret: idus-key

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true